server:
  port: 8020
  shutdown: graceful
   
spring:
  application:
    name: posts-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/pthore
    username: devuser
    password: root

logging:
  level:
    root: info